---
# tasks file for jenkins_install

- name: Shutdown tomcat
  shell: bash /opt/tomcat/bin/shutdown.sh

- name: Download Jenkins
  get_url:
    url: "{{jenkins_url}}"
    dest: /opt/tomcat/webapps

- name: Inatall Jenkins
  shell: nohup java -Djenkins.install.runSetupWizard=false -jar /opt/tomcat/webapps/jenkins.war &

- name: Configure Global Security "Enable security"
  template: src=jenkins_config.xml dest='/root/.jenkins/config.xml'

- name: Startup tomcat
  shell: nohup /opt/tomcat/bin/startup.sh &

- name: Shutdown and Startup tomcat
  shell: bash /opt/tomcat/bin/{{ item }}
  loop:
    - shutdown.sh
    - startup.sh
